apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: cal
  template:
    metadata:
      labels:
        app: cal
    spec:
      containers:
      - image: hemanthc12/httpd
        name: httpd
        ports:
        - containerPort: 80